StationaryReuse/StationaryReuse/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from myapp import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('registration/', views.UserRegistrationView, name="user_registration"),
    path('login/', views.UserLoginView, name="user_login"),
    path('user/', include('myapp.urls')),
    path('', views.HomePageView, name="home"),
    path('<str:username>/postad/', views.PostAdView, name="postad"),
    path('ad-description/<int:pk>/', views.AdDescriptionView, name="ad_description")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

StationaryReuse/myapp/urls.py
from django.conf.urls import include
from django.urls import path
from myapp import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'user'

urlpatterns = [
    path('<str:username>/', views.UserProfileView, name="profile"),
    path('<str:username>/editprofile/', views.UserEditProfileView, name="edit_profile")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

StationaryReuse/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class UserInfoModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to="photos/userprofilepics", blank=True)
    description = models.CharField(max_length=250, blank=True)
    phone_number = models.PositiveSmallIntegerField()
    college = models.CharField(max_length=40, blank=True)
    branch = models.CharField(max_length=40, blank=True)
    address = models.CharField(max_length=50)
    gender = models.CharField(max_length=10, default="Male", blank=True, null=True)
    
    def __str__(self):
        return self.user.username


class AdsInfoModel(models.Model):
    user = models.ForeignKey(UserInfoModel, on_delete=models.CASCADE, related_name="posted_ads")
    purpose = models.CharField(max_length=10)
    category = models.CharField(max_length=10)
    title = models.CharField(max_length=50)
    price = models.FloatField(blank=True)
    description = models.TextField()
    posted_date = models.DateField()
    
    def __str__(self):
        return self.title


class AdsPhotosModel(models.Model):
    pic_parent = models.ForeignKey(AdsInfoModel, on_delete=models.CASCADE, related_name="photos")
    photo = models.ImageField(upload_to="photos/adpics")


class FavouriteAdsModel(models.Model):
    user = models.ForeignKey(UserInfoModel, on_delete=models.CASCADE, related_name="favourite_ads")
    ad = models.OneToOneField(AdsInfoModel, on_delete=models.CASCADE)

StationaryReuse/myapp/forms.py
from django import forms
from django.contrib.auth.models import User


class UserRegistrationModelForm(forms.ModelForm):
    ConfirmPassword = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ['username', 'email', 'password']

    def clean(self):
        user_data = super().clean()
        if user_data['password'] != user_data['ConfirmPassword']:
            raise forms.ValidationError("Passwords did not match!")
        return user_data


class UserLoginModelForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ['username','password']


class UserInfoModelForm(forms.ModelForm):
    pass

StationaryReuse/myapp/views.py
from django.shortcuts import render
from myapp.forms import UserLoginModelForm, UserRegistrationModelForm
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView
from django.contrib.auth.models import User
from myapp.models import UserInfoModel, AdsInfoModel, AdsPhotosModel, FavouriteAdsModel
from django.urls import reverse
from django.utils import timezone

# Create your views here.

def UserLoginView(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponse("user Logged In Successfully")
        else:
            return HttpResponse("YOU MADE A BLUNDER")
    else:
        return render(request, 'myapp/UserLogin.html')


def UserRegistrationView(request):
    if request.method=="POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        password = request.POST.get("password")
        confirm_password = request.POST.get("confirm_password")
        if password == confirm_password:
            user = User.objects.create(username=username, email=email, password=password)
            user.set_password(user.password)
            user.save()
            return HttpResponse("USER REGISTRATION SUCCESSFUL")
        else:
            return HttpResponse("INVALID CREDENTIALS!")
    else:
        return render(request, 'myapp/UserRegistration.html')


def UserProfileView(request, username):
    user = User.objects.get(username=username)
    info = UserInfoModel.objects.get(user=user)
    var_dict = {"user": user, "info": info}
    return render(request, "myapp/profile.html", context=var_dict)


def UserEditProfileView(request, username):
    user = User.objects.get(username=username)
    info = UserInfoModel.objects.get(user=user)
    if request.method == "POST":
        name = str(request.POST.get("name"))
        #checking whether the user has entered the full name of just the first name and inserting the data accordingly in the table.
        if " " in name:
            user.first_name, user.last_name = name.split(" ")
        else:
            user.first_name = name
            user.last_name = ""
        user.email = request.POST.get("email")
        info.gender = request.POST.get("gender")
        info.college = request.POST.get("college")
        info.course = request.POST.get("course")
        info.description = request.POST.get("description")
        info.phone_number = request.POST.get("phone_number")
        info.address = request.POST.get("address")
        if "profile_pic" in request.FILES:
            info.profile_pic = request.FILES.get("profile_pic")
        user.save()
        info.save()
        return HttpResponseRedirect(reverse("user:profile", kwargs={"username":username}))
    else:
        var_dict = {"user":user, "info":info}
        return render(request, "myapp/edit_profile.html", context=var_dict)


def HomePageView(request):
    return render(request, "myapp/home.html", context={})


def PostAdView(request, username):
    user = User.objects.get(username=username)
    info = UserInfoModel.objects.get(user=user)
    if request.method == "POST":
        category = request.POST.get("category")
        title = request.POST.get("title")
        description = request.POST.get("description")
        purpose = request.POST.get("purpose")
        price = request.POST.get("price")
        posted_date = timezone.now()
        # Price in case of donation is a null string so filtering that out.
        if price=="":
            price = 0
        ad = AdsInfoModel.objects.create(title=title, category=category, description=description, purpose=purpose, price=price, user=info, posted_date=posted_date)
        ad.save()
        for pic in request.FILES:
            pic_instance = AdsPhotosModel.objects.create(pic_parent=ad, photo=request.FILES['ad_pic'])
            pic_instance.save()
        return HttpResponse("ad created successfully")

    else:
        return render(request, "myapp/postad.html", context={"user": user, "info": info})


def AdDescriptionView(request, pk):
    ad = AdsInfoModel.objects.get(id=pk)
    var_dict = {'ad': ad}
    return render(request, "myapp/ad_description.html", context=var_dict)

StationaryReuse/templates/myapp/UserLogin.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Login</title>
	<link rel="stylesheet" type="text/css" href="{% static "myapp/css/style.css" %}">
	<link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
	<script src="https://kit.fontawesome.com/a81368914c.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<img class="wave" src="{% static "myapp/images/wave.png" %}">
	<div class="container">
		<div class="img">
			<img src="{% static "myapp/images/bg.svg" %}">
		</div>
		<div class="login-content">
			<form method="POST">
				{% csrf_token %}
				<img src="{% static "myapp/images/avatar.svg" %}">
				<h2 class="title">Welcome</h2>
           		<div class="input-div one">
           		   <div class="i">
           		   		<i class="fas fa-user"></i>
           		   </div>
           		   <div class="div">
           		   		<h5>Username</h5>
           		   		<input type="text" class="input" name="username">
           		   </div>
           		</div>
           		<div class="input-div pass">
           		   <div class="i"> 
           		    	<i class="fas fa-lock"></i>
           		   </div>
           		   <div class="div">
           		    	<h5>Password</h5>
           		    	<input type="password" class="input" name="password">
            	   </div>
            	</div>
            	<a href="#">Forgot Password?</a>
            	<input type="submit" class="btn" value="Login">
            </form>
        </div>
    </div>
    <script type="text/javascript" src="{% static "myapp/javascript/main.js" %}"></script>
</body>
</html>

StationaryReuse/templates/myapp/UserRegistration.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>SignUp</title>
	<link rel="stylesheet" type="text/css" href="{% static "myapp/css/style.css" %}">
	<link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
	<script src="https://kit.fontawesome.com/a81368914c.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<img class="wave" src="{% static "myapp/images/wave.png" %}">
	<div class="container">
		<div class="img">
			<img src="{% static "myapp/images/bg.svg" %}">
		</div>
		<div class="login-content">
			<form method="POST">
                {% csrf_token %}
				<img src="{% static "myapp/images/avatar.svg" %}">
				<h2 class="title">Sign-Up</h2>

           		<div class="input-div one">
           		   <div class="i">
           		   		<i class="fas fa-user"></i>
           		   </div>
           		   <div class="div">
           		   		<h5>Username</h5>
           		   		<input type="text" class="input" name="username">
           		   </div>


           		</div>
				   <div class="input-div email">
					<div class="i">
							<i class="fas fa fa-envelope"></i>
					</div>
					<div class="div">
							<h5>Email</h5>
							<input type="text" class="input" name="email">
					</div>
				 </div>


           		<div class="input-div pass">
           		   <div class="i"> 
           		    	<i class="fas fa-lock"></i>
           		   </div>
           		   <div class="div">
           		    	<h5>Password</h5>
           		    	<input type="password" class="input" name="password">
            	   </div>
            	</div>
                
				<div class="input-div pass">
					<div class="i"> 
						 <i class="fas fa-lock"></i>
					</div>
					<div class="div">
						 <h5>Confirm Password</h5>
						 <input type="password" class="input" name="confirm_password">
				 </div>
			  </div>


            	<a href="#">Forgot Password?</a>
            	<input type="submit" class="btn" value="Submit">
            </form>
        </div>
    </div>
    <script type="text/javascript" src="{% static "myapp/javascript/main.js" %}"></script>
</body>
</html>

StationaryReuse/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>Profile | SR</title>
        <!-- Required meta tags always come first -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static "myapp/css/profile.css" %}">
        <link rel="stylesheet" href="{% static "myapp/css/navigation.css" %}">
        <link rel="stylesheet" href="{% static "myapp/css/footer.css" %}">
    </head>
    <body>
      <nav class="navigation">
        <div class="navigation__column">
            <a href="feed.html">
                <img src="{% static "myapp/images/logo.png" %}" />
            </a>
        </div>
        <div class="navigation__column">
            <i class="fa fa-search"></i>
            <input type="text" placeholder="Search">
        </div>
        <div class="navigation__column">
            <ul class="navigations__links">
                <li class="navigation__list-item">
                    <a href="explore.html" class="navigation__link">
                        <i class="fa fa-compass fa-lg"></i>
                    </a>
                </li>
                <li class="navigation__list-item">
                    <a href="favouriteads.html" class="navigation__link">
                        <i class="fa fa-heart-o fa-lg"></i>
                    </a>
                </li>
                <li class="navigation__list-item">
                    <a href="profile.html" class="navigation__link">
                        <i class="fa fa-user-o fa-lg"></i>
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    {% block body_block %}
    {% endblock %}

    <footer class="footer-distributed">

        <div class="footer-left">
    
          <h3>iPassword<span>Generator</span></h3>
    
          <p class="footer-links">
            <a href="#">Privacy Policy</a>
            -
            <a href="#">Disclaimer</a>
            -
            <a href="#">About Us</a>
    
          </p>
    
          <p class="footer-company-name">Made By Dillip &copy; 2020</p>
        </div>
    
        <div class="footer-center">
    
          <div>
            <i class="fa fa-map-marker"></i>
            <p><span>FM Square, Balasore</span>Odisha, INDIA</p>
          </div>
    
          <div>
            <i class="fa fa-phone"></i>
            <p>+91 9692324552</p>
          </div>
    
          <div>
            <i class="fa fa-envelope"></i>
            <p><a href="mailto:support@company.com">contact@webdevtrick.com</a></p>
          </div>
    
        </div>
    
        <div class="footer-right">
    
          <p class="footer-company-about">
            <span>About the company</span>
            Web Dev Trick is a blog for web designers, graphic designers, web developers &amp; SEO Learner.
          </p>
    
          <div class="footer-icons">
    
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-github"></i></a>
    
          </div>
    
        </div>
    
    </footer>
    
                
    </body>
</html>

StationaryReuse/templates/myapp/edit_profile.html
{% load static %}
<html>
    <head>
        <title>edit profile</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static "myapp/css/edit_profile.css" %}">
        <link rel="stylesheet" href="{% static "myapp/css/navigation.css" %}">
        <link rel="stylesheet" href="{% static "myapp/css/footer.css" %}">
    </head>
    <body>
        <nav class="navigation">
            <div class="navigation__column">
                <a href="feed.html">
                    <img src="{% static "myapp/images/logo.png" %}" />
                </a>
            </div>
            <div class="navigation__column">
                <i class="fa fa-search"></i>
                <input type="text" placeholder="Search">
            </div>
            <div class="navigation__column">
                <ul class="navigations__links">
                    <li class="navigation__list-item">
                        <a href="explore.html" class="navigation__link">
                            <i class="fa fa-compass fa-lg"></i>
                        </a>
                    </li>
                    <li class="navigation__list-item">
                        <a href="favouriteads.html" class="navigation__link">
                            <i class="fa fa-heart-o fa-lg"></i>
                        </a>
                    </li>
                    <li class="navigation__list-item">
                        <a href="profile.html" class="navigation__link">
                            <i class="fa fa-user-o fa-lg"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <div class="container">
            <!-- <div class="row">
                <ol class="col-12 breadcrumb">
                    <li class="breadcrumb-item"><a href="./index.html">Home</a> </li>
                    <li class="breadcrumb-item active">Edit Profile</li>
                </ol>
                <div class="col-12">
                    <h3>Edit Profile</h3>
                    <hr>
                </div>
            </div> -->
            <div class="row">
                <div class="col-12">
                  <h3>Edit Profile</h3>
                  <hr color="black">
                </div>
              </div>
            <div class="view-account">
                <section class="module">
                    <div class="module-inner">
                        <div class="side-bar">
                            <div class="user-info">
                                <img class="img-profile img-circle img-responsive center-block" src="{{info.profile_pic.url}}" alt="">
                                <ul class="meta list list-unstyled">
                                    <li class="name">{{user.get_full_name}}
                                        <!-- <label class="label label-info">{{info.description}}</label> -->
                                    </li>
                                    <li class="email"><a href="#">{{user.email}}</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="content-panel">
                            <h2 class="title">Profile</h2>
                            <form class="form-horizontal" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <fieldset class="fieldset">
                                    <h3 class="fieldset-title">Personal Info</h3>
                                    <div class="form-group avatar">
                                        <figure class="figure col-md-2 col-sm-3 col-xs-12">
                                            <img class="img-rounded img-responsive" src="{{info.profile_pic.url}}" alt="">
                                        </figure>
                                        <div class="form-inline col-md-10 col-sm-9 col-xs-12">
                                            <input type="file" class="file-uploader pull-left" name="profile_pic">
                                            <!-- <button type="submit" class="btn btn-sm btn-default-alt pull-left" formaction="{% url "user:edit_profile" username=user.username %}">Update Image</button> -->
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-2 col-sm-3 col-xs-12 control-label">User Name</label>
                                        <div class="col-md-10 col-sm-9 col-xs-12">
                                            <input type="text" class="form-control" value="{{user.username}}" name="" disabled>
                                        </div>
                                    </div>
                
                                    <div class="form-group">
                                        <label class="col-md-2 col-sm-3 col-xs-12 control-label">Name</label>
                                        <div class="col-md-10 col-sm-9 col-xs-12">
                                            <input type="text" class="form-control" value="{{user.get_full_name}}" name="name" required>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-2 col-sm-3 col-xs-12 control-label">Gender</label>
                                        <div class="col-md-10 col-sm-9 col-xs-12">
                                            <select class="form-control" name="gender" >
                                                <option value="{{info.gender}}" selected>{{info.gender|upper}}</option>
                                                <option value="male">MALE</option>
                                                <option value="female">FEMALE</option>
                                                <option value="other">OTHER</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-2 col-sm-3 col-xs-12 control-label">Course</label>
                                        <div class="col-md-10 col-sm-9 col-xs-12">
                                            <input type="text" class="form-control" value="{{info.branch|upper}}" name="course">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-2 col-sm-3 col-xs-12 control-label">College</label>
                                        <div class="col-md-10 col-sm-9 col-xs-12">
                                            <input type="text" class="form-control" value="{{info.college|title}}" name="college">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-2 col-sm-3 col-xs-12 control-label">Address</label>
                                        <div class="col-md-10 col-sm-9 col-xs-12">
                                            <input type="text" class="form-control" value="{{info.address|title}}" name="address">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-2 col-sm-3 col-xs-12 control-label">About</label>
                                        <div class="col-md-10 col-sm-9 col-xs-12">
                                        <textarea class="form-control" cols="50" rows="4" name="description">{{info.description|safe|linebreaksbr}}</textarea>
                                    </div>

                                </fieldset>
                                <fieldset class="fieldset">
                                    <h3 class="fieldset-title">Contact Info</h3>
                                    <div class="form-group">
                                        <label class="col-md-2  col-sm-3 col-xs-12 control-label">Email</label>
                                        <div class="col-md-10 col-sm-9 col-xs-12">
                                            <input type="email" class="form-control" value="{{user.email}}" name="email" required>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-2  col-sm-3 col-xs-12 control-label">Phone Number</label>
                                        <div class="col-md-10 col-sm-9 col-xs-12">
                                            <input type="number" class="form-control" value="{{info.phone_number}}" name="phone_number" required>
                                        </div>
                                    </div>
                                </fieldset>
                            <hr>
                            <div class="form-group">
                                <div class="col-md-10 col-sm-9 col-xs-12 col-md-push-2 col-sm-push-3 col-xs-push-0">
                                    <input class="btn btn-primary" type="submit" value="Update Profile">
                                </div>
                            </div>
                            </form>
                        </div>
                    </div>
                </section>
            </div>
        </div>


        <footer class="footer-distributed">

            <div class="footer-left">
        
              <h3>iPassword<span>Generator</span></h3>
        
              <p class="footer-links">
                <a href="#">Privacy Policy</a>
                -
                <a href="#">Disclaimer</a>
                -
                <a href="#">About Us</a>
        
              </p>
        
              <p class="footer-company-name">Made By Dillip &copy; 2020</p>
            </div>
        
            <div class="footer-center">
        
              <div>
                <i class="fa fa-map-marker"></i>
                <p><span>FM Square, Balasore</span>Odisha, INDIA</p>
              </div>
        
              <div>
                <i class="fa fa-phone"></i>
                <p>+91 9692324552</p>
              </div>
        
              <div>
                <i class="fa fa-envelope"></i>
                <p><a href="mailto:support@company.com">contact@webdevtrick.com</a></p>
              </div>
        
            </div>
        
            <div class="footer-right">
        
              <p class="footer-company-about">
                <span>About the company</span>
                Web Dev Trick is a blog for web designers, graphic designers, web developers &amp; SEO Learner.
              </p>
        
              <div class="footer-icons">
        
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-linkedin"></i></a>
                <a href="#"><i class="fa fa-github"></i></a>
        
              </div>
        
            </div>
        
        </footer>
  
          
        
    </body>
</html><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

StationaryReuse/templates/myapp/footer.html
<!DOCTYPE html>
<!-- code by webdevtrick ( https://webdevtrick.com ) -->
<html>

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="keywords" content="footer, address, phone, icons" />

  <title>Footer With Address And Phones</title>

  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
  <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="css/footer.css">

</head>

<body>
  
  <footer class="footer-distributed">

    <div class="footer-left">

      <h3>iPassword<span>Generator</span></h3>

      <p class="footer-links">
        <a href="#">Privacy Policy</a>
        -
        <a href="#">Disclaimer</a>
        -
        <a href="#">About Us</a>

      </p>

      <p class="footer-company-name">Made By Dillip &copy; 2020</p>
    </div>

    <div class="footer-center">

      <div>
        <i class="fa fa-map-marker"></i>
        <p><span>FM Square, Balasore</span>Odisha, INDIA</p>
      </div>

      <div>
        <i class="fa fa-phone"></i>
        <p>+91 9692324552</p>
      </div>

      <div>
        <i class="fa fa-envelope"></i>
        <p><a href="mailto:support@company.com">contact@webdevtrick.com</a></p>
      </div>

    </div>

    <div class="footer-right">

      <p class="footer-company-about">
        <span>About the company</span>
        Web Dev Trick is a blog for web designers, graphic designers, web developers &amp; SEO Learner.
      </p>

      <div class="footer-icons">

        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-linkedin"></i></a>
        <a href="#"><i class="fa fa-github"></i></a>

      </div>

    </div>

  </footer>

</body>

</html>